AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack with Two Nested Stacks

Parameters:
  pArtifactBucket:
    Type: String
    Description: Parameter for the Parent Stack

Resources:
  SecurityNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${pArtifactBucket}.s3.ap-south-1.amazonaws.com/templates/security_template.yml  
      Parameters:
        AdministratorAccountId: Test
        RoleName: AWSCloudFormationStackSetExecutionRole

  S3NestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${pArtifactBucket}.s3.ap-south-1.amazonaws.com/templates/s3_template.yml  
      Parameters:
        pBucketName1: cft-deploy-bucket-1
        pBucketName2: cft-deploy-bucket-2
